podcast-title: The Commons Church - Sermon Podcast
podcast-author: The Commons
podcast-subtitle: Official Sermon Audio of The Commons Church in San Diego.
podcast-image: THECOMMONSpodcast.jpg
podcast-description: This is the official audio podcast of The Commons, a church located in the North Park neighborhood of San Diego. The Commons is a community conspiring to proclaim the Cross, cultivating disciples, embracing the oppressed, and inviting you to join the movement. To learn more about us visit our web site at www.thecommonsforall.com
podcast-link: http://www.thecommonsforall.com
podcast-language: en-us
podcast-copyright:
podcast-category: Religion & Spirituality
media-path: media
public-media-path: http://thecommonsforall.com/sermons/media
