podcast-title: The Commons Church - Sermon Podcast
podcast-author: The Commons Church
podcast-subtitle: Official Sermon Audio of The Commons Church in South San Diego.
podcast-image: THECOMMONSpodcast.jpg
podcast-description: This is the official audio podcast of The Commons Church; a community that worships God, imitates Jesus, walks with the Spirit, and partners for the Kingdom. To learn more about us, visit our web site at www.thecommons.church
podcast-link: http://www.thecommons.church
podcast-language: en-us
podcast-copyright:
podcast-category: Religion & Spirituality
media-path: media
public-media-path: http://thecommons.church/sermons/media
